### PR TITLE
build: bundle the library in angular package format

### PR DESCRIPTION
**Pull request by mattlewis92**
I was trying out our app with the new ivy compiler and this package wasn't working with it because it wasn't in the angular package format, this refactors all the build process to use `ng-packagr` which nicely takes care of all the hard work. Thanks for your work on this library! 😄 

Note: After this change you will need to run `npm publish dist` to publish new versions, as everything will get built into the dist folder instead.

### CODE REVIEW

**Comment by mattlewis92** [comment]
@bootsoon I synced with master so this should be good to go now, let me know if you'd like me to change anything! 😄

**Comment by bootsoon** [comment]
Thanks. I'm not familiar with ng-packagr so not sure about this merge.

**Comment by mattlewis92** [comment]
Happy to explain more! ng-packagr takes care of bundling packages into all the formats described by the angular package format: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx

It provides a UMD bundle, ES modules with both ES5 and ES6 as well as several other formats (it's the same format that angular itself is bundled in well as any libraries created with the angular cli). By using ng-packagr and being in the common format angular libraries are created in it improves compatibility with the angular eco system so things like the new ivy compiler just work and don't require changes. 

It shouldn't be a breaking change to your library and actually improves things by removing the need for a lot of build tooling.

If you need any more info please don't hesitate to ask 😄

**Comment by Ezard** [comment]
@bootsoon have you thought about this any more please?

As for the credibility of ng-packagr, it's very widely used, as I believe most Angular libraries use it these days 🙂

**Pull request merged**
